FROM alpine

RUN apk update \
    && apk add lighttpd \
    && rm -rf /var/cache/apk/*

RUN apk --no-cache --update add jq curl bash

COPY /html/ /var/www/localhost/htdocs
COPY *.sh /
WORKDIR /
RUN chmod +x /*.sh
EXPOSE 80

CMD ["/start.sh"]